##Spring Configuration
server:
  port: 8080
spring:
  application:
    name: solicitudes
  devtools:
    add-properties: false
adapters:
  r2dbc:
    host: ${DB_HOST:localhost}
    port: ${DB_PORT:5441}
    database: ${DB_NAME:solicitudes_db}
    schema: ${DB_SCHEMA:public}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
logging:
  level:
    com:
      crediya: ${LOG_LEVEL:INFO}